### ISSUE TITLE
Client generation via Docker fails

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-python#2]
URL=https://github.com/graphsense/graphsense-openapi/blob/develop/graphsense.yaml
➜  graphsense-python git:(develop) ✗ docker run --rm \
      -v "${PWD}:/build" \
      openapitools/openapi-generator-cli:v5.1.1 \
      generate -i "$URL" \
        -g python \
        -o /build
[main] WARN  i.s.parser.util.DeserializationUtils - Error snake-parsing yaml content
io.swagger.parser.util.DeserializationUtils$SnakeException: Exception safe-checking yaml content  (maxDepth 2000, maxYamlAliasesForCollections 2147483647)

**Comment by myrho** [comment]
Use the raw view of the file: https://raw.githubusercontent.com/graphsense/graphsense-openapi/develop/graphsense.yaml
:smile:
