### ISSUE TITLE
Support for pandas dataframes

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-python#8]
The API currently returns data as arrays of JSON objects. On the client side people often work with pandas dataframes and must convert these arrays. Since this is repetitive, it would be great if the API could offer retrieved data optionally also flattened dataframe. Here is. the code I am using for the conversion:

```
lst = []
cols = ['address', 'total_received', 'balance', 'first_tx', 'last_tx', 'btc_senders', 'btc_recipients']
for a in address_details.values():
    lst.append([a['address'],
                a['total_received']['eur'],
                a['balance']['eur'],
                datetime.utcfromtimestamp(a['first_tx']['timestamp']).strftime('%Y-%m-%d %H:%M:%S'),
                datetime.utcfromtimestamp(a['last_tx']['timestamp']).strftime('%Y-%m-%d %H:%M:%S'),
                a['in_degree'],
                a['out_degree']
               ],    
              )

df1 = pd.DataFrame(lst, columns=cols)
```

**Comment by myrho** [comment]
You can create dataframes directly from the CSV endpoints. For instance:

```python 
df = pandas.read_csv(api_instance.list_entity_addresses_csv(currency, 1, _preload_content=False))
```

I'll add examples to the docs, ok?

**Comment by behas** [comment]
Thanks for clarification; adding an example is certainly a first step. However, I'd argue it is a bit counter-intuitive.

Is it, in general possible, to wrap the low-level automatically generated API into a higher-level API? I'm imagining a single module that mirrors the API and just hides all the details underneath.

**Comment by behas** [comment]
How would this work if data is retrieved in chunks? This would then 1 df per chunk, right? It is possible to concat df, but that it is not encouraged in pandas because it is slow.

**Comment by myrho** [comment]
I guess by "hiding details underneath" you mean retrieving large data sets transparently, ie. in a streaming way?

**Comment by behas** [comment]
streaming in the sense of iterating under the hood and then returning a final combined dataframe. I will put the procedures I am using into separate module and then we can discuss API usability issues.

**Comment by myrho** [comment]
obsolete due to new `bulk` endpoint
